# Aggregate data/stores-raw.csv into data/regions.js (per-province 1st-prize win counts).
$ErrorActionPreference = "Stop"

$root = Split-Path -Parent $PSScriptRoot
$csvFile = Join-Path $root "data\stores-raw.csv"
$outFile = Join-Path $root "data\regions.js"

$rows = Import-Csv $csvFile

$counts = @{}
$online = 0
$resolved = 0
$rounds = $rows | ForEach-Object { [int]$_.round } | Sort-Object -Unique

$byRoundMap = @{}
foreach ($n in $rounds) { $byRoundMap["$n"] = New-Object 'System.Collections.Generic.List[object]' }

foreach ($r in $rows) {
    if ([string]::IsNullOrWhiteSpace($r.name)) { continue } # round with 0 winning stores

    if ([string]::IsNullOrWhiteSpace($r.region)) {
        $online++
        $byRoundMap[$r.round].Add([PSCustomObject]@{ name = $r.name; address = $r.address; region = '' })
        continue
    }

    if (-not $counts.ContainsKey($r.region)) { $counts[$r.region] = 0 }
    $counts[$r.region] = $counts[$r.region] + 1
    $resolved++
    $byRoundMap[$r.round].Add([PSCustomObject]@{ name = $r.name; address = $r.address; region = $r.region })
}

$countsObj = [ordered]@{}
foreach ($k in ($counts.Keys | Sort-Object)) { $countsObj[$k] = $counts[$k] }

$byRoundObj = [ordered]@{}
foreach ($n in $rounds) {
    $byRoundObj["$n"] = @($byRoundMap["$n"].ToArray())
}

$result = [PSCustomObject]@{
    roundRange   = @([int]($rounds | Select-Object -First 1), [int]($rounds | Select-Object -Last 1))
    resolved     = $resolved
    onlineWins   = $online
    counts       = $countsObj
    byRound      = $byRoundObj
}

$json = $result | ConvertTo-Json -Compress -Depth 8
$js = "// Auto-generated by scripts/build-regions.ps1 from data/stores-raw.csv.`nwindow.LOTTO_REGIONS = $json;`n"
[System.IO.File]::WriteAllText($outFile, $js, (New-Object System.Text.UTF8Encoding($true)))

Write-Host "Done: $outFile"
Write-Host "Resolved (physical store) wins: $resolved, Online wins: $online"
$countsObj.GetEnumerator() | ForEach-Object { Write-Host "$($_.Key): $($_.Value)" }
