# Fetch all lotto draw results and write data/draws.js
# Source: https://github.com/smok95/lotto (GitHub Pages mirror, round 1 to latest)
$ErrorActionPreference = "Stop"

$root = Split-Path -Parent $PSScriptRoot
$outFile = Join-Path $root "data\draws.js"

Write-Host "Fetching all draw results..."
$resp = Invoke-WebRequest -Uri "https://smok95.github.io/lotto/results/all.json" -TimeoutSec 60 -UseBasicParsing
$draws = $resp.Content | ConvertFrom-Json

Write-Host "Received $($draws.Count) draws. Converting..."

$compact = foreach ($d in $draws) {
    $firstPrize = $null
    $firstWinners = $null
    if ($d.divisions -and $d.divisions.Count -ge 1) {
        $firstPrize = $d.divisions[0].prize
        $firstWinners = $d.divisions[0].winners
    }
    [PSCustomObject]@{
        no      = $d.draw_no
        date    = ([string]$d.date).Substring(0, 10)
        nums    = $d.numbers
        bonus   = $d.bonus_no
        prize1  = $firstPrize
        wins1   = $firstWinners
    }
}

$json = $compact | ConvertTo-Json -Compress -Depth 4
$js = "// Auto-generated by scripts/fetch-draws.ps1. Rounds 1-$($draws[-1].draw_no).`nwindow.LOTTO_DRAWS = $json;`n"
[System.IO.File]::WriteAllText($outFile, $js, [System.Text.Encoding]::UTF8)

Write-Host "Done: $outFile ($($compact.Count) records)"
